export const events = [
  {
    title: "Google I/O 2025",
    slug: "google-io-2025",
    image: "/images/event1.png",
    location: "Mountain View, CA",
    date: "2025-05-20",
    time: "10:00 AM PDT",
  },
  {
    title: "React Summit Amsterdam",
    slug: "react-summit-amsterdam",
    image: "/images/event2.png",
    location: "Amsterdam, Netherlands",
    date: "2025-06-13",
    time: "9:00 AM CEST",
  },
  {
    title: "AWS re:Invent 2025",
    slug: "aws-reinvent-2025",
    image: "/images/event3.png",
    location: "Las Vegas, NV",
    date: "2025-12-01",
    time: "8:00 AM PST",
  },
  {
    title: "GitHub Universe 2025",
    slug: "github-universe-2025",
    image: "/images/event4.png",
    location: "San Francisco, CA",
    date: "2025-10-28",
    time: "9:00 AM PDT",
  },
  {
    title: "Next.js Conf 2025",
    slug: "nextjs-conf-2025",
    image: "/images/event5.png",
    location: "Online",
    date: "2025-10-23",
    time: "10:00 AM PDT",
  },
  {
    title: "Global AI Hackathon",
    slug: "global-ai-hackathon",
    image: "/images/event6.png",
    location: "New York, NY",
    date: "2025-09-06",
    time: "9:00 AM EDT",
  },
];
